FROM elasticsearch:2.3.5

RUN ./bin/plugin install lmenezes/elasticsearch-kopf/v2.1.2
RUN ./bin/plugin install mobz/elasticsearch-head
RUN ./bin/plugin install http://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/delete-by-query/
2.3.5/delete-by-query-2.3.5.zip